import { Token } from "@block-wallet/background/controllers/erc-20/Token"
import { Network } from "@block-wallet/background/utils/constants/networks"
import { Currency } from "@block-wallet/background/utils/currency"
import { searchTokenInAssetsList } from "../context/commActions"

export interface OnRamperToken {
    code: string
    name: string
    network: string
}

export const ONRAMPER_API_KEY = "pk_prod_01GYCJHNRP0V65F272K4Z02JY0"

export const ONRAMPER_FIAT: Currency[] = [
    { code: "AED", name: "UAE-Dirham" },
    { code: "AFN", name: "Afghanistan Afghani" },
    { code: "ALL", name: "Albania Lek" },
    { code: "AMD", name: "Armenian dram" },
    { code: "ANG", name: "Netherlands Antilles Guilder" },
    { code: "AOA", name: "Kwanza" },
    { code: "ARS", name: "Argentina Peso" },
    { code: "AUD", name: "Australia Dollar" },
    { code: "AWG", name: "Aruba Guilder" },
    { code: "AZN", name: "Azerbaijan Manat" },
    { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark" },
    { code: "BBD", name: "Barbados Dollar" },
    { code: "BDT", name: "Bangladeshi Taka" },
    { code: "BGN", name: "Bulgaria Lev" },
    { code: "BHD", name: "Bahraini dinar" },
    { code: "BMD", name: "Bermuda Dollar" },
    { code: "BND", name: "Brunei Darussalam Dollar" },
    { code: "BOB", name: "Bolivia Bolíviano" },
    { code: "BRL", name: "Brazil Real" },
    { code: "BSD", name: "Bahamas Dollar" },
    { code: "BWP", name: "Botswana Pula" },
    { code: "BYN", name: "Belarus Ruble" },
    { code: "BZD", name: "Belize Dollar" },
    { code: "CAD", name: "Canada Dollar" },
    { code: "CHF", name: "Switzerland Franc" },
    { code: "CLP", name: "Chile Peso" },
    { code: "CNY", name: "China Yuan Renminbi" },
    { code: "COP", name: "Colombia Peso" },
    { code: "CRC", name: "Costa Rica Colon" },
    { code: "CUP", name: "Cuba Peso" },
    { code: "CZK", name: "Czech Republic Koruna" },
    { code: "DJF", name: "Djibouti Franc" },
    { code: "DKK", name: "Denmark Krone" },
    { code: "DOP", name: "Dominican Republic Peso" },
    { code: "EGP", name: "Egypt Pound" },
    { code: "EUR", name: "Euro Member Countries" },
    { code: "FJD", name: "Fiji Dollar" },
    { code: "FKP", name: "Falkland Islands (Malvinas) Pound" },
    { code: "GBP", name: "United Kingdom Pound" },
    { code: "GEL", name: "Lari" },
    { code: "GGP", name: "Guernsey Pound" },
    { code: "GHS", name: "Ghana Cedi" },
    { code: "GIP", name: "Gibraltar Pound" },
    { code: "GTQ", name: "Guatemala Quetzal" },
    { code: "GYD", name: "Guyana Dollar" },
    { code: "HKD", name: "Hong Kong Dollar" },
    { code: "HNL", name: "Honduras Lempira" },
    { code: "HRK", name: "Croatia Kuna" },
    { code: "HUF", name: "Hungary Forint" },
    { code: "IDR", name: "Indonesia Rupiah" },
    { code: "ILS", name: "Israel Shekel" },
    { code: "IMP", name: "Isle of Man Pound" },
    { code: "INR", name: "India Rupee" },
    { code: "IRR", name: "Iran Rial" },
    { code: "ISK", name: "Iceland Krona" },
    { code: "JEP", name: "Jersey Pound" },
    { code: "JMD", name: "Jamaica Dollar" },
    { code: "JOD", name: "Jordanian Dinar" },
    { code: "JPY", name: "Japan Yen" },
    { code: "KES", name: "Kenyan Shilling" },
    { code: "KGS", name: "Kyrgyzstan Som" },
    { code: "KHR", name: "Cambodia Riel" },
    { code: "KMF", name: "Comoro Franc" },
    { code: "KPW", name: "Korea (North) Won" },
    { code: "KRW", name: "Korea (South) Won" },
    { code: "KWD", name: "Kuwaiti Dinar" },
    { code: "KYD", name: "Cayman Islands Dollar" },
    { code: "KZT", name: "Kazakhstan Tenge" },
    { code: "LAK", name: "Laos Kip" },
    { code: "LBP", name: "Lebanon Pound" },
    { code: "LKR", name: "Sri Lanka Rupee" },
    { code: "LRD", name: "Liberia Dollar" },
    { code: "MAD", name: "Moroccan-dirham" },
    { code: "MDL", name: "Moldovan Leu" },
    { code: "MGA", name: "Malagasy Ariary" },
    { code: "MKD", name: "Macedonia Denar" },
    { code: "MNT", name: "Mongolia Tughrik" },
    { code: "MOP", name: "Macanese pataca" },
    { code: "MRU", name: "Ouguiya" },
    { code: "MUR", name: "Mauritius Rupee" },
    { code: "MVR", name: "Maldivian rufiyaa" },
    { code: "MWK", name: "Malawian Kwacha" },
    { code: "MXN", name: "Mexico Peso" },
    { code: "MYR", name: "Malaysia Ringgit" },
    { code: "MZN", name: "Mozambique Metical" },
    { code: "NAD", name: "Namibia Dollar" },
    { code: "NGN", name: "Nigeria Naira" },
    { code: "NIO", name: "Nicaragua Cordoba" },
    { code: "NOK", name: "Norway Krone" },
    { code: "NPR", name: "Nepal Rupee" },
    { code: "NZD", name: "New Zealand Dollar" },
    { code: "OMR", name: "Oman Rial" },
    { code: "PAB", name: "Panama Balboa" },
    { code: "PEN", name: "Peru Sol" },
    { code: "PGK", name: "Kina" },
    { code: "PHP", name: "Philippines Peso" },
    { code: "PKR", name: "Pakistan Rupee" },
    { code: "PLN", name: "Poland Zloty" },
    { code: "PYG", name: "Paraguay Guarani" },
    { code: "QAR", name: "Qatar Riyal" },
    { code: "RON", name: "Romania Leu" },
    { code: "RSD", name: "Serbia Dinar" },
    { code: "RUB", name: "Russia Ruble" },
    { code: "RWF", name: "Rwanda Franc" },
    { code: "SAR", name: "Saudi Arabia Riyal" },
    { code: "SBD", name: "Solomon Islands Dollar" },
    { code: "SCR", name: "Seychelles Rupee" },
    { code: "SEK", name: "Sweden Krona" },
    { code: "SGD", name: "Singapore Dollar" },
    { code: "SHP", name: "Saint Helena Pound" },
    { code: "SLL", name: "leone" },
    { code: "SOS", name: "Somalia Shilling" },
    { code: "SRD", name: "Suriname Dollar" },
    { code: "STN", name: "Dobra" },
    { code: "SVC", name: "El Salvador Colon" },
    { code: "SYP", name: "Syria Pound" },
    { code: "SZL", name: "Lilangeni" },
    { code: "THB", name: "Thailand Baht" },
    { code: "TJS", name: "Somoni" },
    { code: "TMT", name: "Turkmenistan New Manat" },
    { code: "TOP", name: "Pa’anga" },
    { code: "TRY", name: "Turkey Lira" },
    { code: "TTD", name: "Trinidad and Tobago Dollar" },
    { code: "TVD", name: "Tuvalu Dollar" },
    { code: "TWD", name: "Taiwan New Dollar" },
    { code: "TZS", name: "Tanzanian Shilling" },
    { code: "UAH", name: "Ukraine Hryvnia" },
    { code: "UGX", name: "UGX" },
    { code: "USD", name: "United States Dollar" },
    { code: "UYU", name: "Uruguay Peso" },
    { code: "UZS", name: "Uzbekistan Som" },
    { code: "VEF", name: "Venezuela Bolívar" },
    { code: "VND", name: "Viet Nam Dong" },
    { code: "XAF", name: "CFA Franc BEAC" },
    { code: "XCD", name: "East Caribbean Dollar" },
    { code: "XOF", name: "CFA Franc BCEAO" },
    { code: "YER", name: "Yemen Rial" },
    { code: "ZAR", name: "South Africa Rand" },
    { code: "ZMW", name: "Zambian Kwacha" },
    { code: "ZWD", name: "Zimbabwe Dollar" },
]

export const ONRAMPER_CRYPTO: OnRamperToken[] = [
    { code: "$FJB", name: "Freedom. Jobs. Business", network: "bsc" },
    { code: "1INCH", name: "1inch Network (BEP-20)", network: "bsc" },
    { code: "1INCH", name: "1INCH (ethereum)", network: "mainnet" },
    { code: "GMT", name: "stepn", network: "solana" },
    { code: "GST", name: "Green Satoshi Token", network: "solana" },
    { code: "KLV", name: "Klever (TRC20)", network: "tron" },
    { code: "NFT", name: "APENFT", network: "tron" },
    { code: "SUN", name: "Sun", network: "tron" },
    { code: "AAVE", name: "Aave", network: "bsc" },
    { code: "AAVE", name: "Aave", network: "mainnet" },
    { code: "AAVE", name: "Aave (polygon)", network: "polygon" },
    { code: "ACH", name: "ACH", network: "bsc" },
    { code: "ACH", name: "ACH", network: "mainnet" },
    { code: "ADA", name: "Cardano", network: "cardano" },
    { code: "ADA", name: "Cardano", network: "bsc" },
    { code: "ADAI", name: "Aave DAI", network: "polygon" },
    { code: "ADX", name: "Ambire AdEx", network: "bsc" },
    { code: "ADX", name: "Ambire AdEx", network: "mainnet" },
    { code: "AERGO", name: "Aergo", network: "mainnet" },
    { code: "AGEUR", name: "agEUR", network: "mainnet" },
    { code: "AGEUR", name: "agEUR", network: "polygon" },
    { code: "AGIX", name: "SingularityNET", network: "mainnet" },
    { code: "AION", name: "Aion", network: "aion" },
    { code: "AKRO", name: "Akropolis", network: "mainnet" },
    { code: "ALGO", name: "Algorand", network: "algorand" },
    { code: "ALICE", name: "MyNeighborAlice", network: "bsc" },
    { code: "ALICE", name: "MyNeighborAlice", network: "mainnet" },
    { code: "ALPACA", name: "ALPACA", network: "bsc" },
    { code: "ALPACA", name: "ALPACA", network: "fantom" },
    {
        code: "AMKT",
        name: "Alongside Crypto Market Index",
        network: "mainnet",
    },
    { code: "AMP", name: "Amp", network: "mainnet" },
    { code: "ANKR", name: "ANKR", network: "mainnet" },
    { code: "ANT", name: "Aragon", network: "mainnet" },
    { code: "APE", name: "ApeCoin", network: "mainnet" },
    { code: "APE", name: "ApeCoin", network: "bsc" },
    { code: "APT", name: "Aptos", network: "aptos" },
    { code: "AR", name: "Arweave", network: "arweave" },
    { code: "ARDR", name: "Ardor", network: "ardor" },
    { code: "ARK", name: "Ark", network: "ark" },
    { code: "ARPA", name: "ARPA Chain", network: "mainnet" },
    { code: "ARV", name: "Ariva", network: "bsc" },
    { code: "AST", name: "AirSwap", network: "mainnet" },
    { code: "ASTR", name: "Astar", network: "astar" },
    { code: "ATA", name: "Automata Network", network: "bsc" },
    { code: "ATA", name: "Automata Network", network: "mainnet" },
    { code: "ATOM", name: "Cosmos", network: "cosmos" },
    { code: "ATOM", name: "ATOM", network: "bsc" },
    { code: "AUDIO", name: "Audius", network: "mainnet" },
    { code: "AURORA", name: "Aurora", network: "aurora" },
    { code: "AURORA", name: "Aurora", network: "mainnet" },
    { code: "AVA", name: "Travala", network: "bbc" },
    { code: "AVA", name: "Travala", network: "bbc" },
    { code: "AVA", name: "Travala", network: "bsc" },
    { code: "AVA", name: "Travala", network: "mainnet" },
    { code: "AVAX", name: "Avalanche (X-CHAIN)", network: "bsc" },
    { code: "AVAX", name: "Avalanche (C-Chain)", network: "avaxcchain" },
    { code: "AVAX", name: "Avalanche (X-Chain)", network: "avaxxchain" },
    { code: "AVN", name: "AVNRich Token", network: "bsc" },
    { code: "AWC", name: "Atomic Wallet Coin", network: "bbc" },
    { code: "AWC", name: "Atomic Wallet Coin", network: "bsc" },
    { code: "AWC", name: "Atomic Wallet Coin", network: "mainnet" },
    { code: "AXS", name: "Axie Infinity", network: "mainnet" },
    { code: "AXS", name: "Axie Infinity", network: "bsc" },
    { code: "AXS", name: "Axie Infinity", network: "ronin" },
    { code: "BABYDOGE", name: "Baby Doge Coin", network: "bsc" },
    { code: "BAKE", name: "BakeryToken", network: "bsc" },
    { code: "BAL", name: "Balancer", network: "bsc" },
    { code: "BAL", name: "Balancer", network: "mainnet" },
    { code: "BAND", name: "Band (ERC20)", network: "bsc" },
    { code: "BAND", name: "Band (ERC20)", network: "mainnet" },
    { code: "BAT", name: "Basic Attention Token", network: "bbc" },
    { code: "BAT", name: "Basic Attention Token", network: "mainnet" },
    { code: "BAT", name: "Basic Attention", network: "polygon" },
    { code: "BAT", name: "Basic Attention", network: "solana" },
    { code: "BCD", name: "Bitcoin Diamond", network: "bitcoindiamond" },
    { code: "BCH", name: "Bitcoin Cash", network: "bitcoincash" },
    { code: "BCH", name: "Bitcoin Cash", network: "bsc" },
    { code: "BEL", name: "Bella Protocol", network: "bsc" },
    { code: "BEL", name: "Bella Protocol", network: "mainnet" },
    { code: "BELT", name: "BELT", network: "bsc" },
    { code: "BHAT", name: "BHNetwork", network: "multiversx" },
    { code: "BIFI", name: "Beefy.Finance", network: "bsc" },
    { code: "BIN", name: "Binemon", network: "bsc" },
    { code: "BIT", name: "BitDAO", network: "mainnet" },
    { code: "BLOCKS", name: "BLOCKS", network: "mainnet" },
    { code: "BLZ", name: "Bluzelle", network: "bsc" },
    { code: "BLZ", name: "Bluzelle", network: "mainnet" },
    { code: "BNB", name: "Binance Coin (BEP-2)", network: "bbc" },
    { code: "BNB", name: "Binance Coin (BEP-20)", network: "bsc" },
    { code: "BNT", name: "BancorNetworkToken", network: "bsc" },
    { code: "BNT", name: "BancorNetworkToken", network: "mainnet" },
    { code: "BOLT", name: "Bolt", network: "mainnet" },
    { code: "BRG", name: "Bridge Oracle", network: "bsc" },
    { code: "BRISE", name: "Bitgert Token", network: "bitgert" },
    { code: "BRISE", name: "Bitgert Token", network: "bsc" },
    { code: "BSV", name: "Bitcoin SV", network: "bsv" },
    { code: "BSW", name: "Biswap", network: "bsc" },
    { code: "BTC", name: "Bitcoin", network: "bitcoin" },
    { code: "BTCB", name: "Bitcoin BEP2", network: "bsc" },
    { code: "BTFA", name: "Banana Task Force Ape", network: "mainnet" },
    { code: "BTG", name: "Bitcoin Gold", network: "bitcoingold" },
    { code: "BTT", name: "BitTorrent (Binance Smart Chain)", network: "bsc" },
    { code: "BTTC", name: "BitTorrent Token", network: "tron" },
    { code: "BUSD", name: "Binance USD (BEP-2)", network: "bbc" },
    { code: "BUSD", name: "Binance USD", network: "avaxcchain" },
    { code: "BUSD", name: "Binance USD", network: "bsc" },
    { code: "BUSD", name: "BUSD", network: "mainnet" },
    { code: "BUSD", name: "Binance USD", network: "polygon" },
    { code: "C98", name: "C98", network: "bsc" },
    { code: "C98", name: "C98", network: "mainnet" },
    { code: "CAKE", name: "PancakeSwap", network: "bsc" },
    { code: "CAPS", name: "CAPS", network: "bsc" },
    { code: "CEL", name: "Celsius", network: "mainnet" },
    { code: "CELL", name: "Cellframe", network: "mainnet" },
    { code: "CELO", name: "Celo native asset", network: "celo" },
    { code: "CELR", name: "Celer Network", network: "bsc" },
    { code: "CELR", name: "Celer Network", network: "mainnet" },
    { code: "CEUR", name: "Celo Euro", network: "celo" },
    { code: "CFX", name: "Conflux", network: "bsc" },
    { code: "CHAIN", name: "Chain Games", network: "mainnet" },
    { code: "CHAIN", name: "Chain Games (Polygon)", network: "polygon" },
    { code: "CHESS", name: "Tranchess", network: "bsc" },
    { code: "CHR", name: "Chromia", network: "bsc" },
    { code: "CHR", name: "Chromia", network: "mainnet" },
    { code: "CHSB", name: "SwissBorg", network: "mainnet" },
    { code: "CHZ", name: "Chiliz", network: "mainnet" },
    { code: "CKB", name: "Nervos Network", network: "nervos" },
    { code: "CLV", name: "Clover Finance", network: "mainnet" },
    { code: "CNS", name: "Centric Swap", network: "bsc" },
    { code: "COMP", name: "Compound", network: "bsc" },
    { code: "COMP", name: "Compound", network: "mainnet" },
    { code: "COTI", name: "COTI", network: "bsc" },
    { code: "COTI", name: "COTI", network: "mainnet" },
    { code: "CREAL", name: "Celo Brazilian Real", network: "celo" },
    { code: "CRO", name: "Cronos", network: "cronos" },
    { code: "CRO", name: "Crypto.Com", network: "cryptocom" },
    { code: "CRO", name: "Crypto.Com", network: "mainnet" },
    { code: "CRV", name: "Curve DAO Token", network: "mainnet" },
    { code: "CSPR", name: "Casper (Mainnet)", network: "casper" },
    { code: "CTSI", name: "Cartesi", network: "mainnet" },
    { code: "CTSI", name: "Cartesi", network: "bsc" },
    { code: "CUDOS", name: "CUDOS", network: "mainnet" },
    { code: "CULT", name: "Cult DAO", network: "mainnet" },
    { code: "CUSD", name: "Celo Dollar", network: "celo" },
    { code: "CVC", name: "Civic", network: "mainnet" },
    { code: "CVX", name: "Convex Finance", network: "mainnet" },
    { code: "DAI", name: "DAI", network: "bsc" },
    { code: "DAI", name: "Dai Stablecoin", network: "mainnet" },
    { code: "DAI", name: "Dai Stablecoin", network: "optimism" },
    { code: "DAI", name: "Dai Stablecoin", network: "palm" },
    { code: "DAI", name: "Dai", network: "polygon" },
    { code: "DAI", name: "Dai Stablecoin", network: "zksync" },
    { code: "DAIE", name: "Bridged DAI", network: "avaxcchain" },
    { code: "DAO", name: "DAO Maker", network: "mainnet" },
    { code: "DASH", name: "Dash", network: "dash" },
    { code: "DCR", name: "Decred", network: "decred" },
    { code: "DEFIT", name: "Digital Fitness", network: "mainnet" },
    { code: "DENT", name: "Dent", network: "mainnet" },
    { code: "DFI", name: "DeFiChain", network: "dfi" },
    { code: "DFYN", name: "Dfyn Network", network: "polygon" },
    { code: "DGB", name: "DigiByte", network: "digibyte" },
    { code: "DIA", name: "DIA", network: "bsc" },
    { code: "DIA", name: "DIA", network: "mainnet" },
    { code: "DOBO", name: "Dogebonk", network: "bsc" },
    { code: "DOCK", name: "Dock", network: "dock" },
    { code: "DOGE", name: "DogeCoin", network: "dogecoin" },
    { code: "DOGE", name: "Dogecoin", network: "bsc" },
    { code: "DOT", name: "Polkadot", network: "polkadot" },
    { code: "DOT", name: "Polkadot", network: "bsc" },
    { code: "DPI", name: "DeFiPulse Index", network: "mainnet" },
    { code: "DUSK", name: "Dusk Network", network: "bsc" },
    { code: "DUSK", name: "Dusk Network", network: "mainnet" },
    { code: "DYDX", name: "dYdX", network: "mainnet" },
    { code: "EGLD", name: "MultiversX", network: "multiversx" },
    { code: "EGLD", name: "MultiversX", network: "bsc" },
    { code: "EKTA", name: "EKTA", network: "ekta" },
    { code: "ELF", name: "aelf", network: "bsc" },
    { code: "ELF", name: "aelf", network: "mainnet" },
    { code: "ELON", name: "Dogelon Mars", network: "mainnet" },
    { code: "ENJ", name: "Enjin Coin", network: "mainnet" },
    { code: "ENS", name: "ENS", network: "mainnet" },
    { code: "EOS", name: "EOS", network: "eosio" },
    { code: "EOS", name: "EOS", network: "bsc" },
    { code: "ETC", name: "Ethereum Classic", network: "ethereumclassic" },
    { code: "ETC", name: "Ethereum Classic", network: "bsc" },
    { code: "ETH", name: "mainnet", network: "mainnet" },
    { code: "ETH", name: "Ethereum (Arbitrum)", network: "arbitrum" },
    { code: "ETH", name: "mainnet", network: "bsc" },
    { code: "ETH", name: "Ethereum (Immutable X)", network: "immutable" },
    { code: "ETH", name: "Ethereum (Loopring)", network: "loopring" },
    { code: "ETH", name: "mainnet", network: "optimism" },
    { code: "ETH", name: "mainnet", network: "starknet" },
    { code: "ETH", name: "mainnet", network: "zksync" },
    { code: "EURL", name: "Lugh", network: "mainnet" },
    { code: "EURL", name: "Lugh", network: "tezos" },
    { code: "EURT", name: "Euro Tether", network: "mainnet" },
    { code: "EVED", name: "Evedo", network: "mainnet" },
    { code: "FARM", name: "HarvestFinance", network: "bsc" },
    { code: "FARM", name: "HarvestFinance", network: "mainnet" },
    { code: "FEAR", name: "Fear", network: "polygon" },
    { code: "FEG", name: "FEG Token (Binance Smart Chain)", network: "bsc" },
    {
        code: "FEG",
        name: "FEG Token (Binance Smart Chain)",
        network: "mainnet",
    },
    { code: "FET", name: "Fetch", network: "bsc" },
    { code: "FET", name: "Fetch", network: "mainnet" },
    { code: "FEVR", name: "FEVR Token", network: "bsc" },
    { code: "FEVR", name: "FEVR Token", network: "mainnet" },
    { code: "FIL", name: "Filecoin", network: "filecoin" },
    { code: "FIO", name: "FIO Protocol", network: "fio" },
    { code: "FIRO", name: "Firo", network: "bsc" },
    { code: "FIRO", name: "Firo", network: "firo" },
    { code: "FLOKI", name: "Floki Inu (ERC20)", network: "bsc" },
    { code: "FLOKI", name: "Floki Inu (ERC20)", network: "mainnet" },
    { code: "FLOW", name: "Flow", network: "flow" },
    { code: "FLOW", name: "Flow", network: "bsc" },
    { code: "FLR", name: "Flare", network: "flare" },
    { code: "FLUF", name: "Fluffy Coin", network: "bsc" },
    { code: "FLUX", name: "Flux", network: "bsc" },
    { code: "FLUX", name: "Flux", network: "mainnet" },
    { code: "FOOD", name: "FoodChain Global", network: "polygon" },
    { code: "FRAX", name: "Frax", network: "mainnet" },
    { code: "FRONT", name: "Frontier", network: "bsc" },
    { code: "FRONT", name: "Frontier", network: "mainnet" },
    { code: "FTM", name: "Fantom", network: "fantom" },
    { code: "FTM", name: "Fantom", network: "bsc" },
    { code: "FTM", name: "Fantom", network: "mainnet" },
    { code: "FTT", name: "FTX Token", network: "mainnet" },
    { code: "FUN", name: "FunFair", network: "mainnet" },
    { code: "FUSD", name: "Fantom USD", network: "flow" },
    { code: "FUSD", name: "fUSD token", network: "fuse" },
    { code: "FUSDC", name: "Fake USDC", network: "polygon" },
    { code: "FUSE", name: "Fuse", network: "fuse" },
    { code: "FUSE", name: "Fuse Network", network: "mainnet" },
    { code: "GAFA", name: "Gafa (GAFA)", network: "bsc" },
    { code: "GAL", name: "Project Galaxy", network: "bsc" },
    { code: "GAL", name: "Project Galaxy", network: "mainnet" },
    { code: "GALA", name: "Gala", network: "mainnet" },
    { code: "GARI", name: "Gari Network", network: "solana" },
    { code: "GAS", name: "Neo Gas", network: "neo" },
    { code: "GETH", name: "Guarded Ether (ERC20)", network: "mainnet" },
    { code: "GGTKN", name: "GG TOKEN", network: "bsc" },
    { code: "GLM", name: "Golem", network: "mainnet" },
    { code: "GLMR", name: "Glimmer", network: "moonbeam" },
    { code: "GMEE", name: "GAMEE", network: "polygon" },
    { code: "GMT", name: "GMT", network: "bsc" },
    { code: "GMT", name: "stepn", network: "mainnet" },
    { code: "GMX", name: "GMX (Arbitrum)", network: "arbitrum" },
    { code: "GNO", name: "GNO", network: "mainnet" },
    { code: "GODS", name: "Gods Unchained", network: "immutable" },
    { code: "GRT", name: "The Graph", network: "mainnet" },
    { code: "GT", name: "Gatechain Token", network: "mainnet" },
    { code: "GTC", name: "Gitcoin", network: "mainnet" },
    { code: "GTH", name: "Gather", network: "mainnet" },
    { code: "GUSD", name: "Gemini Dollar", network: "mainnet" },
    { code: "HAI", name: "HAI", network: "vechain" },
    { code: "HBAR", name: "Hedera Hashgraph", network: "hedera" },
    { code: "HEX", name: "HEX", network: "mainnet" },
    { code: "HEZ", name: "Hermez Network", network: "mainnet" },
    { code: "HIVE", name: "Hive", network: "hive" },
    { code: "HMC", name: "Hamdan Coin", network: "bsc" },
    { code: "HNT", name: "Helium", network: "helium" },
    {
        code: "HOGE",
        name: "Hoge Finance (Binance Smart Chain)",
        network: "mainnet",
    },
    { code: "HOT", name: "Holo", network: "mainnet" },
    { code: "HOTCROSS", name: "Hot Cross (HOTCROSS)", network: "bsc" },
    { code: "HT", name: "Huobi Token", network: "mainnet" },
    { code: "HTR", name: "Hathor", network: "hathor" },
    { code: "IBZ", name: "Ibiza Token", network: "mainnet" },
    { code: "IBZ", name: "Ibiza Token", network: "polygon" },
    { code: "ICP", name: "Internet Computer", network: "icp" },
    { code: "ICX", name: "ICON", network: "icon" },
    { code: "IGG", name: "IG Gold", network: "polygon" },
    { code: "ILV", name: "Illuvium", network: "bsc" },
    { code: "ILV", name: "Illuvium", network: "mainnet" },
    { code: "IMX", name: "Immutable X", network: "mainnet" },
    { code: "IMX", name: "Immutable X (Immutable)", network: "immutable" },
    { code: "INJ", name: "Injective", network: "injective" },
    { code: "IOST", name: "IOST", network: "iost" },
    { code: "IOTX", name: "IoTeX", network: "iotex" },
    { code: "JASMY", name: "JasmyCoin", network: "mainnet" },
    { code: "JOE", name: "JOE", network: "avaxcchain" },
    { code: "JST", name: "JUST", network: "bsc" },
    { code: "JST", name: "JUST", network: "tron" },
    { code: "KAVA", name: "Kava", network: "kava" },
    { code: "KDA", name: "Kadena", network: "kadena" },
    { code: "KDOE", name: "Kudoe", network: "mainnet" },
    { code: "KEANU", name: "Keanu Inu", network: "mainnet" },
    { code: "KEY", name: "SelfKey", network: "mainnet" },
    { code: "KIBA", name: "Kiba Inu", network: "bsc" },
    { code: "KIBA", name: "Kiba Inu", network: "mainnet" },
    { code: "KIN", name: "KIN", network: "solana" },
    { code: "KISHU", name: "Kishu Inu", network: "mainnet" },
    { code: "KLAY", name: "Klaytn", network: "klaytn" },
    { code: "KLEE", name: "KleeKai", network: "mainnet" },
    { code: "KLIMA", name: "Klima DAO", network: "polygon" },
    { code: "KMD", name: "Komodo", network: "bsc" },
    { code: "KMD", name: "Komodo", network: "komodo" },
    { code: "KNC", name: "Kyber Network", network: "bsc" },
    { code: "KNC", name: "Kyber Network", network: "mainnet" },
    { code: "KSM", name: "Kusama", network: "kusama" },
    { code: "LBLOCK", name: "lucky block", network: "bsc" },
    { code: "LDO", name: "Lido DAO", network: "mainnet" },
    { code: "LEAD", name: "Lead Wallet", network: "mainnet" },
    { code: "LEASH", name: "LEASH", network: "mainnet" },
    { code: "LGCY", name: "LGCY Network", network: "mainnet" },
    { code: "LINK", name: "Chainlink", network: "mainnet" },
    { code: "LOOKS", name: "LooksRare", network: "mainnet" },
    { code: "LOOM", name: "Loom Network", network: "bsc" },
    { code: "LOOM", name: "Loom Network", network: "mainnet" },
    { code: "LRC", name: "Loopring", network: "loopring" },
    { code: "LRC", name: "Loopring", network: "bsc" },
    { code: "LRC", name: "Loopring", network: "mainnet" },
    { code: "LSK", name: "Lisk", network: "lisk" },
    { code: "LTC", name: "Litecoin", network: "litecoin" },
    { code: "LTC", name: "Litecoin", network: "bsc" },
    { code: "LUFFY", name: "Luffy", network: "mainnet" },
    { code: "LUNA", name: "Terra", network: "terra" },
    { code: "LUNC", name: "Terra Classic", network: "terraclassic" },
    { code: "LXT", name: "Litex", network: "mainnet" },
    { code: "MAGIC", name: "Magic (Arbitrum)", network: "arbitrum" },
    { code: "MANA", name: "Decentraland", network: "bsc" },
    { code: "MANA", name: "Decentraland", network: "mainnet" },
    { code: "MANA", name: "Decentraland", network: "polygon" },
    { code: "MASK", name: "Mask Network", network: "mainnet" },
    { code: "MASK", name: "Mask Network (BEP-20)", network: "bsc" },
    { code: "MATIC", name: "MATIC", network: "polygon" },
    { code: "MATIC", name: "Polygon (Matic)", network: "bsc" },
    { code: "MATIC", name: "Polygon (ERC-20)", network: "mainnet" },
    { code: "MBOX", name: "MBOX", network: "bsc" },
    { code: "MC", name: "Merit Circle", network: "bsc" },
    { code: "MC", name: "Merit Circle", network: "mainnet" },
    { code: "MDA", name: "Moeda Loyalty Points", network: "mainnet" },
    { code: "MDT", name: "Measurable Data Token", network: "bsc" },
    { code: "MDT", name: "Measurable Data Token", network: "mainnet" },
    { code: "MEX", name: "Maiar DEX", network: "multiversx" },
    { code: "MH3", name: "NFT", network: "mainnet" },
    { code: "MIM", name: "Magic Internet Money", network: "mainnet" },
    { code: "MINA", name: "Mina", network: "mina" },
    { code: "MINDS", name: "Minds", network: "mainnet" },
    { code: "MINIFOOTBALL", name: "Minifootball", network: "bsc" },
    { code: "MINT", name: "Mint Club", network: "bsc" },
    { code: "MIOTA", name: "IOTA", network: "iota" },
    { code: "MIR", name: "Mirror Protocol", network: "bsc" },
    { code: "MIR", name: "Mirror Protocol", network: "mainnet" },
    { code: "MKR", name: "Maker", network: "bsc" },
    { code: "MKR", name: "Maker", network: "mainnet" },
    { code: "MNET", name: "MINE Network", network: "mainnet" },
    { code: "MOB", name: "MobileCoin", network: "mobilecoin" },
    { code: "MOMENTO", name: "Momento", network: "bsc" },
    { code: "MONONOKE", name: "Mononoke Inu", network: "mainnet" },
    { code: "MOVR", name: "Moonriver", network: "moonriver" },
    { code: "MPH", name: "88mph", network: "mainnet" },
    { code: "MSU", name: "MetaSoccer", network: "polygon" },
    { code: "MTL", name: "Metal", network: "mainnet" },
    { code: "MTV", name: "MultiVAC (ERC20)", network: "mainnet" },
    { code: "must", name: "Must", network: "polygon" },
    { code: "MX", name: "MX Token", network: "mainnet" },
    { code: "NAFT", name: "Nafter", network: "bsc" },
    { code: "NEAR", name: "NEAR Protocol", network: "near" },
    { code: "NEAR", name: "NEAR Protocol", network: "bsc" },
    { code: "NEO", name: "Neo", network: "neo" },
    { code: "NEXO", name: "Nexo", network: "mainnet" },
    { code: "NEXO", name: "Nexo", network: "polygon" },
    { code: "NFTB", name: "NFTb", network: "bsc" },
    { code: "NIM", name: "Nimiq", network: "nimiq" },
    { code: "NMR", name: "Numeraire", network: "mainnet" },
    { code: "NOW", name: "NOW Token", network: "bbc" },
    { code: "NOW", name: "NOW Token", network: "mainnet" },
    { code: "NWC", name: "Newscrypto", network: "mainnet" },
    { code: "NXUSD", name: "NXUSD", network: "avaxcchain" },
    { code: "NYXT", name: "Nyx Token", network: "mainnet" },
    { code: "OCEAN", name: "Ocean Protocol", network: "mainnet" },
    { code: "OGN", name: "Origin Protocol", network: "mainnet" },
    { code: "OKB", name: "OKB", network: "mainnet" },
    { code: "OKT", name: "OKT", network: "okc" },
    { code: "OM", name: "MANTRA DAO", network: "mainnet" },
    { code: "OM", name: "MANTRA DAO", network: "bsc" },
    { code: "OMG", name: "OMG Network", network: "mainnet" },
    { code: "ONE", name: "Harmony", network: "harmony" },
    { code: "ONG", name: "Ontology Gas", network: "ontology" },
    { code: "ONT", name: "Ontology", network: "bsc" },
    { code: "ONT", name: "Ontology", network: "ontology" },
    { code: "OP", name: "Optimism", network: "optimism" },
    { code: "ORN", name: "Orion (ERC-20)", network: "mainnet" },
    { code: "OSMO", name: "Osmosis", network: "osmosis" },
    { code: "OVR", name: "OVR", network: "polygon" },
    { code: "OXT", name: "Orchid", network: "mainnet" },
    { code: "PAX", name: "Paxos Standard", network: "mainnet" },
    { code: "PAXG", name: "PAX Gold", network: "mainnet" },
    { code: "PAY", name: "TenXPay", network: "mainnet" },
    { code: "PERL", name: "Perlin", network: "bsc" },
    { code: "PERL", name: "Perlin", network: "mainnet" },
    { code: "PIKA", name: "Pika", network: "mainnet" },
    { code: "PIT", name: "Pitbull", network: "bsc" },
    { code: "PIVX", name: "PIVX", network: "pivx" },
    { code: "PLA", name: "PlayDapp", network: "mainnet" },
    { code: "PLA", name: "PlayDapp", network: "polygon" },
    { code: "PLOT", name: "PlotX", network: "mainnet" },
    { code: "PNK", name: "Kleros", network: "mainnet" },
    { code: "POLS", name: "Polkastarter", network: "bsc" },
    { code: "POLS", name: "Polkastarter (Ethereum)", network: "mainnet" },
    { code: "POODL", name: "Poodl Token", network: "bsc" },
    { code: "POWR", name: "Power Ledger", network: "mainnet" },
    { code: "PPM", name: "Punk Panda Coin", network: "bsc" },
    { code: "PPT", name: "Populous", network: "mainnet" },
    { code: "PRIMAL", name: "PRIMAL", network: "mainnet" },
    { code: "PYR", name: "Vulcan Forged PYR", network: "mainnet" },
    { code: "PYR", name: "Vulcan Forged PYR", network: "polygon" },
    { code: "QI", name: "Qi Dao", network: "polygon" },
    { code: "QNT", name: "Quant", network: "mainnet" },
    { code: "QSP", name: "Quantstamp", network: "mainnet" },
    { code: "QTUM", name: "Qtum", network: "qtum" },
    { code: "QUACK", name: "RichQuack", network: "bsc" },
    { code: "QUARTZ", name: "Sandclock", network: "mainnet" },
    { code: "QUICK", name: "Quickswap", network: "polygon" },
    { code: "RACA", name: "RACA", network: "bsc" },
    { code: "RACA", name: "RACA", network: "mainnet" },
    { code: "RAI", name: "Rai Reflex Index", network: "mainnet" },
    { code: "RCN", name: "Ripio Credit Network", network: "mainnet" },
    { code: "RDOC", name: "RIF Dollar", network: "rsk" },
    { code: "REN", name: "Ren", network: "mainnet" },
    { code: "REP", name: "Augur", network: "mainnet" },
    { code: "REVV", name: "REVV", network: "flow" },
    { code: "REVV", name: "REVV", network: "polygon" },
    { code: "RFUEL", name: "Rio DeFi", network: "mainnet" },
    { code: "RIF", name: "RSK Infrastructure Framework", network: "rsk" },
    { code: "RLC", name: "iExec", network: "mainnet" },
    { code: "RLY", name: "Rally", network: "solana" },
    { code: "RLY", name: "Rally", network: "mainnet" },
    { code: "RON", name: "Ronin Token", network: "ronin" },
    { code: "ROOK", name: "KeeperDAO", network: "mainnet" },
    { code: "ROSE", name: "Oasis Network", network: "oasis" },
    { code: "RPL", name: "Rocket Pool", network: "mainnet" },
    { code: "RSR", name: "Reserve Rights", network: "mainnet" },
    { code: "RUNE", name: "THORChain", network: "bbc" },
    { code: "RVN", name: "Ravencoin", network: "ravencoin" },
    { code: "SAITAMA", name: "Saitama", network: "mainnet" },
    { code: "SAND", name: "The Sandbox", network: "mainnet" },
    { code: "SAND", name: "The Sandbox", network: "bsc" },
    { code: "SAND", name: "The Sandbox", network: "polygon" },
    { code: "SANSHU", name: "Sanshu Inu", network: "mainnet" },
    { code: "SC", name: "Siacoin", network: "sia" },
    { code: "SCRT", name: "Secret", network: "secret" },
    { code: "SDN", name: "Shiden Network", network: "Shiden" },
    { code: "SFDAI", name: "Superfluid fDai", network: "polygon" },
    { code: "SFUSDC", name: "Superfluid fUSDC", network: "polygon" },
    { code: "SHIB", name: "Shiba Inu (ERC-20)", network: "mainnet" },
    { code: "SHIB", name: "Shiba Inu", network: "bsc" },
    { code: "SHR", name: "ShareToken", network: "mainnet" },
    { code: "SKILL", name: "SKILL", network: "bsc" },
    { code: "SLP", name: "Smooth Love Potion", network: "ronin" },
    { code: "SNACK", name: "Snack", network: "bsc" },
    { code: "SNM", name: "SONM", network: "bsc" },
    { code: "SNM", name: "SONM", network: "mainnet" },
    { code: "SNT", name: "Status", network: "mainnet" },
    { code: "SNX", name: "Synthetix", network: "bsc" },
    { code: "SNX", name: "Synthetix", network: "mainnet" },
    { code: "SOL", name: "Solana", network: "solana" },
    { code: "SOL", name: "Solana", network: "bsc" },
    { code: "SOLVE", name: "SOLVE", network: "mainnet" },
    { code: "SPA", name: "Sperax Governance Token", network: "arbitrum" },
    { code: "SPI", name: "Shopping.io", network: "mainnet" },
    { code: "SPO", name: "SPO", network: "mainnet" },
    { code: "SPS", name: "Splintershards", network: "bsc" },
    { code: "SPS", name: "Splintershards", network: "mainnet" },
    { code: "SRK", name: "SparkPoint", network: "mainnet" },
    { code: "SRM", name: "Serum", network: "mainnet" },
    { code: "SRM", name: "Serum", network: "solana" },
    { code: "STARL", name: "Starlink", network: "mainnet" },
    { code: "STEEM", name: "Steem", network: "steem" },
    { code: "STETH", name: "Lido Staked Ether", network: "mainnet" },
    { code: "STMX", name: "StormX", network: "mainnet" },
    { code: "STORJ", name: "Storj", network: "mainnet" },
    {
        code: "STPT",
        name: "Standard Tokenization Protocol",
        network: "mainnet",
    },
    { code: "STRAX", name: "Stratis", network: "stratis" },
    { code: "STRX", name: "StrikeX", network: "bsc" },
    { code: "STX", name: "Stacks", network: "stacks" },
    { code: "STXEM", name: "stakedXEM", network: "mainnet" },
    { code: "STXUSDT", name: "Test Staxe USDT", network: "polygon" },
    { code: "SUN", name: "Sun", network: "bsc" },
    { code: "SUPER", name: "SuperFarm", network: "mainnet" },
    { code: "SUSD", name: "SUSD", network: "mainnet" },
    { code: "SUSHI", name: "Sushi", network: "mainnet" },
    { code: "SUSHI", name: "Sushi", network: "bsc" },
    { code: "SUSHI", name: "Sushi", network: "polygon" },
    { code: "SWAP", name: "Trustswap", network: "mainnet" },
    { code: "SWAPP", name: "SWAPP Protocol", network: "mainnet" },
    { code: "SWEAT", name: "Sweat (Near)", network: "near" },
    { code: "SWFTC", name: "SwftCoin", network: "mainnet" },
    { code: "SXP", name: "Swipe", network: "swipe" },
    { code: "SYS", name: "Syscoin", network: "syscoin" },
    { code: "TAMA", name: "Tamadoge", network: "mainnet" },
    { code: "TFUEL", name: "Theta Fuel", network: "theta" },
    { code: "THETA", name: "THETA", network: "theta" },
    { code: "TIPSY", name: "TipsyCoin", network: "bsc" },
    { code: "TKO", name: "Toko Token", network: "bsc" },
    { code: "TLM", name: "TLM", network: "bsc" },
    { code: "TLM", name: "TLM", network: "mainnet" },
    { code: "TOMO", name: "TomoChain", network: "tomochain" },
    { code: "TON", name: "The Open Network", network: "ton" },
    { code: "TON", name: "TON", network: "everscale" },
    { code: "TRIBE", name: "Tribe", network: "mainnet" },
    { code: "TRVL", name: "Dtravel", network: "mainnet" },
    { code: "TRX", name: "TRON", network: "tron" },
    { code: "TRX", name: "TRON", network: "bsc" },
    { code: "TSX", name: "TradeStars", network: "mainnet" },
    { code: "TSX", name: "TradeStars", network: "polygon" },
    { code: "TT", name: "ThunderCore", network: "thundercore" },
    { code: "TUSD", name: "TrueUSD", network: "mainnet" },
    { code: "TUSD", name: "TrueUSD", network: "avaxcchain" },
    { code: "TUSD", name: "TrueUSD", network: "bsc" },
    { code: "TUSD", name: "TrueUSD", network: "tron" },
    { code: "TWT", name: "TWT", network: "bbc" },
    { code: "TWT", name: "TWT", network: "bsc" },
    { code: "TXL", name: "Tixl", network: "mainnet" },
    { code: "UBT", name: "Unibright", network: "mainnet" },
    { code: "UFO", name: "UFO Gaming", network: "mainnet" },
    { code: "UMA", name: "UMA", network: "mainnet" },
    { code: "UNFI", name: "Unifi Protocol DAO", network: "bsc" },
    { code: "UNFI", name: "Unifi Protocol DAO", network: "mainnet" },
    { code: "UNI", name: "Uniswap", network: "mainnet" },
    { code: "UNI", name: "Uniswap", network: "bsc" },
    { code: "UOS", name: "Ultra", network: "mainnet" },
    { code: "URUS", name: "Urus", network: "mainnet" },
    { code: "USDC", name: "USD Coin", network: "algorand" },
    { code: "USDC", name: "USD Coin (Aptos)", network: "aptos" },
    { code: "USDC", name: "USD Coin (Arbitrum)", network: "arbitrum" },
    { code: "USDC", name: "USD Coin", network: "avaxcchain" },
    { code: "USDC", name: "USD Coin", network: "bsc" },
    { code: "USDC", name: "USD Coin", network: "mainnet" },
    { code: "USDC", name: "USD Coin (Flow)", network: "flow" },
    { code: "USDC", name: "USD Coin (Fuse)", network: "fuse" },
    { code: "USDC", name: "USD Coin (Hadera)", network: "hedera" },
    { code: "USDC", name: "USD Coin (loopring)", network: "loopring" },
    { code: "USDC", name: "USD Coin (Optimism)", network: "optimism" },
    { code: "USDC", name: "USD Coin (Polygon)", network: "polygon" },
    { code: "USDC", name: "USD Coin", network: "ronin" },
    { code: "USDC", name: "USD Coin (Solana)", network: "solana" },
    { code: "USDC", name: "USD Coin (Stellar)", network: "stellar" },
    { code: "USDC", name: "USD Coin (Tron)", network: "tron" },
    { code: "USDC", name: "USD Coin (zkSync)", network: "zksync" },
    { code: "USDCE", name: "Bridged USDC.e", network: "avaxcchain" },
    { code: "USDP", name: "USDP", network: "mainnet" },
    { code: "USDS", name: "Sperax USD", network: "arbitrum" },
    { code: "USDT", name: "Tether", network: "algorand" },
    { code: "USDT", name: "USDT", network: "avaxcchain" },
    { code: "USDT", name: "Tether (bsc)", network: "bsc" },
    { code: "USDT", name: "Tether", network: "mainnet" },
    { code: "USDT", name: "USDT", network: "everscale" },
    { code: "USDT", name: "Tether", network: "omni" },
    { code: "USDT", name: "Tether (polygon)", network: "polygon" },
    { code: "USDT", name: "Tether (solana)", network: "solana" },
    { code: "USDT", name: "Tether", network: "tron" },
    { code: "USDT", name: "Tether", network: "zksync" },
    { code: "USN", name: "USN", network: "near" },
    { code: "UTK", name: "Utrust", network: "mainnet" },
    { code: "UTK", name: "Utrust", network: "multiversx" },
    { code: "VERSE", name: "Verse", network: "mainnet" },
    { code: "VET", name: "VeChain", network: "vechain" },
    { code: "VET", name: "VeChain", network: "bsc" },
    { code: "VIB", name: "Viberate", network: "mainnet" },
    { code: "VLX", name: "Velas", network: "velas" },
    { code: "VLX", name: "Velas", network: "velasevm" },
    { code: "VOLT", name: "Volt Inu V2", network: "bsc" },
    { code: "VOLT", name: "Volt Inu V2", network: "mainnet" },
    { code: "VOXEL", name: "Voxies (Polygon)", network: "polygon" },
    { code: "VRA", name: "Verasity", network: "mainnet" },
    { code: "WABI", name: "Tael", network: "mainnet" },
    { code: "WAN", name: "Wanchain", network: "wanchain" },
    { code: "WAVES", name: "Waves", network: "waves" },
    { code: "WAVES", name: "Waves", network: "bsc" },
    { code: "WAVES", name: "Waves", network: "mainnet" },
    { code: "WAXP", name: "WAX", network: "wax" },
    { code: "WBTC", name: "Wrapped Bitcoin", network: "mainnet" },
    { code: "WBTC", name: "Wrapped Bitcoin", network: "polygon" },
    { code: "WBTC", name: "Wrapped Bitcoin", network: "zksync" },
    { code: "WETH", name: "Wrapped Ether (ERC-20)", network: "mainnet" },
    { code: "WETH", name: "Wrapped Ether", network: "polygon" },
    { code: "ETH", name: "mainnet", network: "ronin" },
    { code: "WISE", name: "Wise Token", network: "mainnet" },
    { code: "WLKN", name: "WLKN", network: "solana" },
    { code: "WOO", name: "WOO Network", network: "bsc" },
    { code: "WOO", name: "WOO Network", network: "mainnet" },
    { code: "WORLD", name: "World Token", network: "mainnet" },
    { code: "WRX", name: "WazirX", network: "bsc" },
    { code: "WTC", name: "Waltonchain", network: "mainnet" },
    { code: "WXT", name: "Wirex", network: "avaxcchain" },
    { code: "XCAD", name: "XCAD Network", network: "zilliqa" },
    { code: "XCUR", name: "Curate", network: "mainnet" },
    { code: "XDAI", name: "xDAI", network: "gnosis" },
    { code: "XEM", name: "NEM", network: "nem" },
    { code: "XIO", name: "XIO", network: "mainnet" },
    { code: "XLM", name: "Stellar Lumens", network: "stellar" },
    { code: "XMR", name: "Monero", network: "monero" },
    { code: "XNO", name: "Nano", network: "nano" },
    { code: "XOR", name: "Sora", network: "mainnet" },
    { code: "XRP", name: "XRP (ripple)", network: "ripple" },
    { code: "XTZ", name: "Tezos", network: "tezos" },
    { code: "XTZ", name: "Tezos", network: "bsc" },
    { code: "XVG", name: "Verge", network: "verge" },
    { code: "XYM", name: "Symbol", network: "symbol" },
    { code: "XYO", name: "XYO", network: "mainnet" },
    { code: "YFI", name: "yearn.finance", network: "bsc" },
    { code: "YFI", name: "yearn.finance", network: "mainnet" },
    { code: "YFII", name: "YFII.finance", network: "mainnet" },
    { code: "YLD", name: "Yield", network: "mainnet" },
    { code: "YOOSHI", name: "YooShi", network: "bsc" },
    { code: "ZEC", name: "Zcash", network: "zcash" },
    { code: "ZEN", name: "Horizen", network: "horizen" },
    { code: "ZIL", name: "ZIL", network: "bsc" },
    { code: "ZIL", name: "Zilliqa", network: "zilliqa" },
    { code: "ZOON", name: "ZOON", network: "bsc" },
    { code: "ZPAY", name: "ZoidPay", network: "multiversx" },
    { code: "ZRX", name: "0x", network: "mainnet" },
    { code: "ZUSD", name: "Digital USD", network: "mainnet" },
]

export const getOnRamperTokenByNetwork = async (currentNetwork: Network) => {
    const networkTokenList: Token[] = []

    const networkTokens = ONRAMPER_CRYPTO.filter(
        (c) => c.network.toLowerCase() === currentNetwork.name.toLowerCase()
    )
    console.log(networkTokens)
    networkTokens.forEach((token) => {
        searchTokenInAssetsList(token.code, true).then((result) => {
            if (result && result.tokens[0]) {
                networkTokenList.push(result.tokens[0])
            }
        })
    })
    console.log(networkTokenList)
    return networkTokenList
}
