PURPLE      := $(shell tput setaf 129)
GRAY        := $(shell tput setaf 245)
GREEN       := $(shell tput setaf 34)
BLUE        := $(shell tput setaf 25)
YELLOW      := $(shell tput setaf 3)
WHITE       := $(shell tput setaf 7)
RESET       := $(shell tput sgr0)
