name: Convention

on:
  pull_request:
    branches:
      - master

  repository_dispatch:
    types: [automation]
env:
  CONVENTION: "^(chore|docs|feat|fix|refactor|style|test)"

jobs:
  commits:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, node]
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v2

      - name: Validate commits convention
        run: |
          commits=$(git log master^..HEAD --oneline)
          regex=$CONVENTION"{1}(\([[:alnum:]._-]+\))?(!)?: ([[:alnum:]])+([[:space:][:print:][:punct:]]*)"
          IFS=$'\n'
          error=
          for commit in $commits
          do
              message=$(echo ${commit:8})
              if [[ ! $message =~ $regex ]]; then
                  echo "Invalid commit: \"$message\"."
                  error=1
              fi
          done

          if [[ ! $error = "" ]]; then
              echo "Fix the commit messages using \"git commit --amend\"."
              exit 1
          fi

      - name: Validate commits convention
        run: |
          regex=$CONVENTION"{1}/([[:alnum:]])+([[:punct:]]*)"
          if [[ ! $GITHUB_REF_NAME =~ $regex ]]; then
              echo "Invalid branch name: \"$GITHUB_REF_NAME\"."
              echo "Create a new branch from this one using a valid name."
              exit 1
          fi
