name: CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - '**.json'
      - '**.html'
      - '**.nvmrc'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      # Fake job to skip the required status checks on the PR
      - name: Skip e2e
        run: |
          echo "No e2e required"
