name: CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - '**.json'
      - '**.html'
      - '**.nvmrc'
      - '!package.json'
      - '!public/manifest.json'
      - '!release-notes.json'
jobs:
  e2e:
    runs-on: ubuntu-latest
    #if: startsWith(github.ref_name, 'docs/') == true || startsWith(github.ref_name, 'chore/') == true || startsWith(github.ref_name, 'release/') == true
    steps:
      # Fake job to skip the required status checks on the PR
      - name: Skip e2e
        run: |
          echo "No e2e required"
