name: Tests

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      cache:
        description: "Delete cache"
        required: false
        default: "true"

  repository_dispatch:
    types: [automation]

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, node]

    steps:
      - run: echo "::set-output name=branch::$(git ls-remote https://${{ secrets.USER_PAT }}:${{ secrets.PAT }}@github.com/block-wallet/extension.git ${{ github.head_ref }})"
        id: monorepo-branch

      - run: echo "::set-output name=branch::$(git ls-remote https://${{ secrets.USER_PAT }}:${{ secrets.PAT }}@github.com/block-wallet/extension-provider.git ${{ github.head_ref }})"
        id: provider-branch

      - run: echo "::set-output name=branch::$(git ls-remote https://${{ secrets.USER_PAT }}:${{ secrets.PAT }}@github.com/block-wallet/extension-ui.git ${{ github.head_ref }})"
        id: ui-branch

      - run: echo "::set-output name=name::background_${{ github.event.number }}_$(date +"%FT%T").zip"
        id: zip

      - run: echo "::set-output name=title::$(gh pr view https://${{ secrets.USER_PAT }}:${{ secrets.PAT }}@github.com/block-wallet/extension-background/pull/${{ github.event.number }} --json title --jq '.title')"
        id: pr

      - name: Checkout monorepo
        uses: actions/checkout@v2
        if: ${{ (steps.monorepo-branch.outputs.branch == '') }}
        with:
          repository: block-wallet/extension
          ref: refs/heads/master
          token: ${{ secrets.PAT }}

      - name: Checkout ui
        uses: actions/checkout@v2
        if: ${{ (steps.ui-branch.outputs.branch == '') }}
        with:
          repository: block-wallet/extension-ui
          ref: refs/heads/master
          path: packages/ui/
          token: ${{ secrets.PAT }}

      - name: Checkout provider
        uses: actions/checkout@v2
        if: ${{ (steps.provider-branch.outputs.branch == '') }}
        with:
          repository: block-wallet/extension-provider
          ref: refs/heads/master
          path: packages/provider/
          token: ${{ secrets.PAT }}

      - name: Checkout monorepo - feature branch
        uses: actions/checkout@v2
        if: ${{ (steps.monorepo-branch.outputs.branch != '') }}
        with:
          repository: block-wallet/extension
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Checkout ui - feature branch
        uses: actions/checkout@v2
        if: ${{ (steps.ui-branch.outputs.branch != '') }}
        with:
          repository: block-wallet/extension-ui
          ref: ${{ github.head_ref }}
          path: packages/ui/
          token: ${{ secrets.PAT }}

      - name: Checkout provider - feature branch
        uses: actions/checkout@v2
        if: ${{ (steps.provider-branch.outputs.branch != '') }}
        with:
          repository: block-wallet/extension-provider
          ref: ${{ github.head_ref }}
          path: packages/provider/
          token: ${{ secrets.PAT }}

      - name: Checkout make scripts
        uses: actions/checkout@v2
        with:
          repository: block-wallet/block-make
          ref: refs/heads/main
          path: .make
          token: ${{ secrets.PAT }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: packages/background/

      - name: Dependencies cache
        id: cache-cypress
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ci-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          make install/ci

      - name: Build extension
        run: ENVIRONMENT=prod make build
        env:
          CI: false

      - name: Zip build
        run: zip -r -D ${{ steps.zip.outputs.name }} dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_RELEASE_BUCKET }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_RELEASE_BUCKET }}
          aws-region: us-east-2

      - name: Upload zip to S3
        run: aws s3 cp ${{ steps.zip.outputs.name }} s3://releases.blockwallet.io/background/tmp/

      - name: Slack notification - CI status
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Slack notification - CI status
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#0d118c",
                  "pretext": "<http://releases.blockwallet.io/background/tmp/${{ steps.zip.outputs.name }}|Download> temp PR build",
                  "author_name": "Background",
                  "author_link": "https://github.com/block-wallet/extension-background",
                  "title": "${{ steps.pr.outputs.title }} #${{ github.event.number }}",
                  "title_link": "https://github.com/block-wallet/extension-background/pull/${{ github.event.number }}",
                  "fields": [
                    {
                        "title": "Branch",
                        "value": "${{ github.head_ref }}",
                        "short": true
                    },
                    {
                        "title": "Commit",
                        "value": "<https://github.com/block-wallet/extension-background/commit/${{github.event.pull_request.head.sha}}|${{github.event.pull_request.head.sha}}>",
                        "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_RELEASES }}

  test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    steps:
      - run: echo "::set-output name=branch::$(git ls-remote https://${{ secrets.USER_PAT }}:${{ secrets.PAT }}@github.com/block-wallet/extension.git ${{ github.head_ref }})"
        id: monorepo-branch

      - run: echo "::set-output name=branch::$(git ls-remote https://${{ secrets.USER_PAT }}:${{ secrets.PAT }}@github.com/block-wallet/extension-provider.git ${{ github.head_ref }})"
        id: provider-branch

      - run: echo "::set-output name=branch::$(git ls-remote https://${{ secrets.USER_PAT }}:${{ secrets.PAT }}@github.com/block-wallet/extension-ui.git ${{ github.head_ref }})"
        id: ui-branch

      - name: Checkout monorepo
        uses: actions/checkout@v2
        if: ${{ (steps.monorepo-branch.outputs.branch == '') }}
        with:
          repository: block-wallet/extension
          ref: refs/heads/master
          token: ${{ secrets.PAT }}

      - name: Checkout ui
        uses: actions/checkout@v2
        if: ${{ (steps.ui-branch.outputs.branch == '') }}
        with:
          repository: block-wallet/extension-ui
          ref: refs/heads/master
          path: packages/ui/
          token: ${{ secrets.PAT }}

      - name: Checkout provider
        uses: actions/checkout@v2
        if: ${{ (steps.provider-branch.outputs.branch == '') }}
        with:
          repository: block-wallet/extension-provider
          ref: refs/heads/master
          path: packages/provider/
          token: ${{ secrets.PAT }}

      - name: Checkout monorepo - feature branch
        uses: actions/checkout@v2
        if: ${{ (steps.monorepo-branch.outputs.branch != '') }}
        with:
          repository: block-wallet/extension
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Checkout ui - feature branch
        uses: actions/checkout@v2
        if: ${{ (steps.ui-branch.outputs.branch != '') }}
        with:
          repository: block-wallet/extension-ui
          ref: ${{ github.head_ref }}
          path: packages/ui/
          token: ${{ secrets.PAT }}

      - name: Checkout provider - feature branch
        uses: actions/checkout@v2
        if: ${{ (steps.provider-branch.outputs.branch != '') }}
        with:
          repository: block-wallet/extension-provider
          ref: ${{ github.head_ref }}
          path: packages/provider/
          token: ${{ secrets.PAT }}

      - name: Checkout make scripts
        uses: actions/checkout@v2
        with:
          repository: block-wallet/block-make
          ref: refs/heads/main
          path: .make
          token: ${{ secrets.PAT }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: packages/background/

      - name: Dependencies cache
        id: cache-cypress
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ci-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          make install/ci

      - name: Test background
        run: make test/background

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
